### ISSUE TITLE
Commit Checklist

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/team4#101]
Hi everyone! :)
As I've been asked to do in #55, here is a short checklist of things we should be aware of when making a new commit or closing an issue:
- [ ] Every commit needs to include a meaningful comment. Pay attention that you reference the issue number you are closing! (use comments on the commit)
- [ ] We must work on the master branch and not creating new braches or making any pull requests.
- [ ] Before pushing your commits, make sure there are no errors nor warrning.
- [ ] Every closed issue should have an assignee and a milestone set to "Sprint 0". 
- [ ] Label any duplicate found issue.

**Comment by yossigil** [comment]
You are still commiting code that break commits. I reopen this. Please find a procedure by which each one you understands and follows the recommendations. Currently this this not the case

**Comment by menhel** [comment]
Duplicate for #107 . Closing.
